[package]
name = "flowchain"
version = "0.0.1"
authors = ["Bryan Chen <bryan@laminar.one>"]
build = "build.rs"
edition = "2018"

[profile.release]
panic = "unwind"

[[bin]]
name = "flowchain"
path = "src/main.rs"

[dependencies]
derive_more = "0.14.0"
exit-future = "0.1"
futures = "0.1"
log = "0.4"
parking_lot = "0.9.0"
tokio = "0.1"
trie-root = "0.15.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
ctrlc = { version = "3.0", features = ["termination"] }
aura-primitives = { package = "substrate-consensus-aura-primitives", git = "https://github.com/paritytech/substrate.git" }
basic-authorship = { package = "substrate-basic-authorship", git = "https://github.com/paritytech/substrate.git" }
consensus = { package = "substrate-consensus-aura", git = "https://github.com/paritytech/substrate.git" }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/paritytech/substrate.git" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate.git" }
network = { package = "substrate-network", git = "https://github.com/paritytech/substrate.git" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate.git" }
sr-io = { git = "https://github.com/paritytech/substrate.git" }
substrate-cli = { git = "https://github.com/paritytech/substrate.git" }
substrate-client = { git = "https://github.com/paritytech/substrate.git" }
substrate-executor = { git = "https://github.com/paritytech/substrate.git" }
substrate-service = { git = "https://github.com/paritytech/substrate.git" }
transaction-pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate.git" }
flowchain-runtime = { path = "runtime" }

[build-dependencies]
vergen = "3"

[workspace]
members = [ "runtime", "modules/*" ]
exclude = [ "runtime/wasm" ]
